# Generated by Django 4.1.2 on 2023-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Mobileno',
            field=models.BigIntegerField(default=1),
        ),
    ]
