# Generated by Django 4.1.2 on 2023-02-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_is_block_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_block',
            new_name='is_access',
        ),
    ]
