# Generated by Django 4.1.2 on 2023-02-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bus_seats_locations_bus_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='bus_id',
            new_name='bus',
        ),
    ]
