# Generated by Django 4.1.2 on 2023-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_bus_id_locations_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
