# Generated by Django 4.1.2 on 2023-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_locations_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='jounery_date',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
