# Generated by Django 4.1.2 on 2023-02-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bus_jounery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AddField(
            model_name='seats',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.bus'),
        ),
    ]
