# Generated by Django 4.1.2 on 2023-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_bus_seats_seats_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='arrival_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
