# Generated by Django 4.1.2 on 2023-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bus_arrival_time_bus_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='jounery_date',
            new_name='arrival_date',
        ),
        migrations.AddField(
            model_name='bus',
            name='Rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_date',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='duration',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
